# Changes here will be overwritten by Copier
_commit: 3f262a8
_src_path: /home/toino/Projects/github/ttoino/templates
description: C++23 Hyprland plugin for CSS-like box shadows
name: shadows-plus-plus
project_type: general

